version: '3.8'

services:
  redis:
    image: redis:8-alpine
    container_name: corrector-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  corrector:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: corrector-app
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - REDIS_ADDR=redis:6379
      - REDIS_PASSWORD=
      - REDIS_DB=0
      - HTTP_ADDR=:8080
      - DICTIONARY_PATH=ru.txt
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      # Если у вас есть дополнительные словари или данные, 
      # которые нужно монтировать извне
      - ./data:/app/data:ro
    # healthcheck:
    #   test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/api/v1/custom-word"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3

volumes:
  redis_data:
    driver: local

networks:
  default:
    name: corrector-network